In [15]:
import numpy as np
import pandas as pd 
import statsmodels.api as sm
import statsmodels.formula.api as smf
import seaborn as sns
from sklearn.preprocessing import scale 
from sklearn.model_selection import train_test_split, GridSearchCV, cross_val_score
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report
from sklearn.metrics import roc_auc_score,roc_curve
import statsmodels.formula.api as smf
import matplotlib.pyplot as plt
from sklearn.neighbors import KNeighborsClassifier
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.naive_bayes import GaussianNB
from sklearn import tree
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import GradientBoostingClassifier
from xgboost import XGBClassifier
from lightgbm import LGBMClassifier
from catboost import CatBoostClassifier

from warnings import filterwarnings
filterwarnings('ignore')

%matplotlib inline

from sklearn.tree import DecisionTreeRegressor 
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import roc_curve
#from mlxtend.feature_selection import ExhaustiveFeatureSelector as EFS
#from mlxtend.feature_selection import SequentialFeatureSelector as SFS
from sklearn.neighbors import KNeighborsRegressor
from sklearn.ensemble import BaggingClassifier
np.random.seed(0)

ModuleNotFoundError: No module named 'xgboost'

In [17]:
df = pd.read_excel("states.xlsx")
df = df.dropna()

In [18]:
df

,Country,"GDP (€, millions)",Accession Year,Council Votes,European Parliament Seats,"GDP per capita ($, millions)","GDP ($, millions)",Population Density,Area (km²),Population
1,2,339896.0,1995.0,10.0,18.0,43775.0,376950.0,102,83855,8576261
2,3,410351.0,1958.0,12.0,21.0,40324.0,455086.0,368,30528,11237274
3,4,45287.0,2007.0,10.0,17.0,6994.0,50199.0,65,110994,7202198
4,5,43847.0,2013.0,7.0,11.0,11536.0,48732.0,75,56594,4225316
5,6,17637.0,2004.0,4.0,6.0,23243.0,19560.0,92,9251,847008
6,7,166964.0,2004.0,12.0,21.0,17548.0,185156.0,134,78866,10538275
7,8,271786.0,1973.0,7.0,13.0,51989.0,295091.0,131,43075,5659715
8,9,20252.0,2004.0,4.0,6.0,17119.0,22459.0,29,45227,1314870
9,10,209511.0,1995.0,7.0,13.0,42311.0,231950.0,16,338424,5471753
10,11,2181064.0,1958.0,29.0,74.0,36206.0,2418836.0,121,549087,66488186
11,12,3032820.0,1958.0,29.0,96.0,41313.0,3363447.0,227,357021,81197537
12,13,175697.0,1981.0,12.0,21.0,18002.0,194851.0,82,131990,10858018
13,14,109674.0,2004.0,12.0,21.0,12364.0,121715.0,106,93030,9855571
15,16,255815.0,1973.0,7.0,11.0,61134.0,283703.0,66,70273,4628949
16,17,1645439.0,1958.0,29.0,73.0,29958.0,1821497.0,202,301338,60795612
17,18,24368.0,2004.0,4.0,8.0,13649.0,27003.0,31,64589,1986096
19,20,37331.0,2004.0,7.0,11.0,14147.0,41171.0,45,65200,2921262
20,21,51216.0,1958.0,4.0,6.0,101450.0,57794.0,218,2586,562958
22,23,9276.0,2004.0,3.0,6.0,22596.0,9746.0,1359,316,429344
24,25,676531.0,1958.0,13.0,26.0,44300.0,750284.0,407,41543,16900726
26,27,429794.0,2004.0,27.0,51.0,12555.0,477066.0,122,312685,38005614
27,28,179540.0,1986.0,12.0,21.0,19222.0,198923.0,112,92390,10374822
28,29,159964.0,2007.0,14.0,32.0,8973.0,177954.0,83,238391,19870647
30,31,78686.0,2004.0,7.0,13.0,16088.0,87264.0,111,49035,5421349
31,32,38570.0,2004.0,4.0,8.0,20727.0,42775.0,102,20273,2062874
32,33,1075639.0,1986.0,27.0,54.0,25832.0,1199057.0,92,504030,46449565
33,34,447010.0,1995.0,10.0,20.0,50580.0,495624.0,22,449964,9747355
36,37,2580065.0,1973.0,29.0,73.0,43876.0,2858003.0,266,243610,64875165

In [19]:
df.describe().T

,count,mean,std,min,25%,50%,75%,max
Country,28.0,1.767857e+01,1.068073e+01,2.0,8.75,16.5,27.25,37.0
"GDP (€, millions)",28.0,5.255011e+05,8.209982e+05,9276.0,44927.00,177618.5,434098.00,3032820.0
Accession Year,28.0,1.988286e+03,1.942098e+01,1958.0,1973.00,1995.0,2004.00,2013.0
Council Votes,28.0,1.257143e+01,8.954323e+00,3.0,7.00,10.0,13.25,29.0
European Parliament Seats,28.0,2.682143e+01,2.493258e+01,6.0,11.00,19.0,27.50,96.0
"GDP per capita ($, millions)",28.0,3.027896e+04,2.056207e+04,6994.0,15602.75,22919.5,42677.00,101450.0
"GDP ($, millions)",28.0,5.825677e+05,9.102429e+05,9746.0,49832.25,196887.0,481705.50,3363447.0
Population Density,28.0,1.709286e+02,2.517618e+02,16.0,72.75,104.0,151.00,1359.0
Area (km²),28.0,1.565773e+05,1.615332e+05,316.0,44689.00,81360.5,258042.00,549087.0
Population,28.0,1.816087e+07,2.348913e+07,429344.0,3899302.50,9161808.0,17643206.25,81197537.0

In [22]:
df = df.copy()
df = df.dropna()
y = df["Country"]
X = df[["GDP","Accession Year","Council Votes","European Parliament Seats","GDP per capita ($, millions)","GDP ($, millions)","Population Density","Area  (km²)","Population"]]

X_train, X_test, y_train, y_test = train_test_split(X, y, 
                                                    test_size=0.20)

KeyError: "['GDP', 'Area  (km²)'] not in index"